### ISSUE TITLE
I have hacked your adapter sorry

### ISSUE THREAD

**Issue by gilles-g** [masbug/flysystem-google-drive-ext#130]
Hello,

One day, I came across an old Symfony project using Flysystem v1 and the "nao-pon/flysystem-google-drive" adapter.

I’m now using your adapter because it’s compatible with Flysystem V3!

However, I couldn't figure out why I couldn’t just use your adapter as-is, so I made a few changes:

I copied and pasted your adapter and added a single line:

```php
public function listContents(string $directory, bool $recursive): iterable
    {
        $this->refreshToken();
        $path = $this->prefixer->prefixPath($directory);

        $this->useDisplayPaths = true; // here
        if ($this->useDisplayPaths) {
```

This is the configuration

```yaml
App\My\Custom\GoogleDriveAdapter:
    arguments:
        - '@Google_Service_Drive'
        - 'wsreerdfEZ21ZSEsdsd'   # before it was only "root", but now it's the root id
        - { useDisplayPaths: false }
```

And now I can have my list

```php
array:17 [▼
  0 => 
League\Flysystem
\
DirectoryAttributes {#9512 ▼
    -type: "dir"
    -path: "1810"
    -visibility: "private"
    -lastModified: 1585300066
    -extraMetadata: array:5 [▶]
  }
  1 => 
League\Flysystem
\
DirectoryAttributes {#9750 ▼
    -type: "dir"
    -path: "489"
    -visibility: "private"
    -lastModified: 1585304995
    -extraMetadata: array:5 [▶]
  }
  2 => 
League\Flysystem
\
DirectoryAttributes {#4905 ▼
    -type: "dir"
    -path: "1411"
    -visibility: "private"
    -lastModified: 1585315255
    -extraMetadata: array:5 [▶]
  }
```

without my line, path is replaced with "token id", and I can't read the name anymore.

I use a service account json to authenticate with Google

```php
        $client = new \Google_Client();
        $client->setAuthConfig($googleCredentialJsonPath);
        $client->addScope(\Google_Service_Drive::DRIVE);
        $client->useApplicationDefaultCredentials(true);
```

Maybe I don't understand how init the configuration?

Thank you :)

**Comment by masbug** [comment]
That is the expected behaviour since you configured the adapter with "useDisplayPaths: false".
Everything is explained in the [README](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/README.md).

**Comment by gilles-g** [comment]
Sorry to reopen it @masbug 

Well, I want to use "useDisplayPaths: true"

I have:  My drive/project name/app one

I just want to list the content of "app one" shared with the service account email, what I need to do for that?


```yaml
    GoogleDriveAdapter:
        arguments:
            - '@Google_Service_Drive'
            - "" # root ? null ? 'project name/app one'   What is the root here?
            - { useDisplayPaths: true }
```

```php
$this->googleDrive->listContents('', true)
```

I tried to pass "project name" or "project name/app one", a lot of combinaison..

I've carefully read the README and examples for Laravel, but I'm missing something and I'm looking for help.

**Comment by gilles-g** [comment]
Ok ok I found

It's the option "sharedFolderId"

``` yaml
    GoogleDriveAdapter:
        arguments:
            - '@Google_Service_Drive'
            - ""
            - { useDisplayPaths: true, sharedFolderId: 'drive_folder' }
```

You can re-close, thanks.
